package com.example.dialogalisa.dto.model;

public enum SessionState {
    INITIAL,
    NULLABLE,
    FIRST_INITIAL,
    SCHOOL_SCHEDULED,
    SCHOOL_EXAMPLE,
    INFO_SKILL,
    COMMAND_END,


    PENDING_NAME,
    PENDING_NEW_TERM,
    PENDING_ENG_TRANSLATION,
    PENDING_RUS_TRANSLATION,
    PENDING_TEST_TYPE_CHOICE,
    PENDING_TEST_RESPONSE,
    PENDING_NEW_USER_NAME,
    PENDING_USER_NAME_TO_SWITCH,
    PENDING_TEST_DICTIONARY
}
